=== PierreTonnelier/Dictionnaire_de_Musique_APP/Structure_0.dtd
<!ELEMENT DMJJR (ARTICLE)+>
<!ELEMENT ARTICLE (CDI, CDT)>
<!ATTLIST ARTICLE RELU (OUI | NON) "NON">
<!ATTLIST ARTICLE id CDATA #REQUIRED >
<!ATTLIST ARTICLE id2 CDATA #IMPLIED > 
<!ATTLIST ARTICLE id3 CDATA #IMPLIED > 
<!ATTLIST ARTICLE id4 CDATA #IMPLIED >
<!ELEMENT CDI ((ITEM | ITEMS), U_GRAMMAIRE?)>
<!ATTLIST U_GRAMMAIRE QUICK (NM|NF|v|adj|adv) #IMPLIED>
<!ELEMENT ITEMS ((ITEM | TXTDisparaitre)+) >
<!ELEMENT CDT ((DEFINITION | CONX)*, U_RENVOI?)>
<!ELEMENT CONX (#PCDATA) >

<!ELEMENT ITEM (#PCDATA|italic)*>
<!ELEMENT U_GRAMMAIRE (texte, GRAMMAIRE*)>
<!ELEMENT GRAMMAIRE (CATEGORIE, GENRE?)*>
<!ELEMENT texte (#PCDATA)>
<!ELEMENT CATEGORIE (SUBSTANTIF | VERBE | ADJECTIF | ADVERBE)>
<!ELEMENT GENRE (MASCULIN | FEMININ | NEUTRE )>
<!ELEMENT DEFINITION (p+)>

<!ELEMENT p (#PCDATA|U_RENVOI|a|sup|italic|bold|RENVOI|AUTRE|GREC|ITEM_TRAITE|LVL|CITATION_CENTRE|CITATION)*>
<!ELEMENT CITATION_CENTRE (#PCDATA)>
<!ELEMENT CITATION (#PCDATA)>
<!ELEMENT LVL (#PCDATA|U_RENVOI|a|sup|italic|bold|RENVOI|AUTRE|GREC|ITEM_TRAITE)*><!-- I. II. III. -->
<!ELEMENT GREC (#PCDATA)>
<!ELEMENT ITEM_TRAITE (#PCDATA)>
<!ELEMENT sup (#PCDATA)>

<!ELEMENT italic (#PCDATA|a|RENVOI)*>

<!ELEMENT a (#PCDATA|RENVOI|italic)*>
<!ATTLIST a class NMTOKEN #REQUIRED>
<!ATTLIST a href CDATA #REQUIRED>

<!ELEMENT U_RENVOI ((TXTDisparaitre, RENVOI, (TXTDisparaitre, RENVOI)*, TXTDisparaitre)* | TXTDisparaitre)>
<!ELEMENT RENVOI (#PCDATA)>
<!ATTLIST RENVOI cible CDATA #REQUIRED>
<!ATTLIST RENVOI planche (OUI) #IMPLIED page CDATA #IMPLIED vignette CDATA #IMPLIED>
<!ELEMENT bold (#PCDATA) >


<!ELEMENT TXTDisparaitre (#PCDATA)><!-- , . ou-->
<!ELEMENT AUTRE (#PCDATA) >
<!ELEMENT ERROR EMPTY>
<!ELEMENT SUBSTANTIF EMPTY>
<!ELEMENT VERBE EMPTY>
<!ELEMENT ADJECTIF EMPTY>
<!ELEMENT MASCULIN EMPTY>
<!ELEMENT FEMININ EMPTY>
<!ELEMENT NEUTRE EMPTY>
<!ELEMENT ADVERBE EMPTY>

=== PierreTonnelier/Dictionnaire_de_Musique_APP/Extrait_DMJJR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DMJJR SYSTEM "../Structure/Structure_0.dtd">
<DMJJR>
	<ARTICLE RELU="OUI" id="DIMINUTION1">
		<CDI>
			<ITEM>DIMINUTION</ITEM>
			<U_GRAMMAIRE QUICK="NF">
				<texte>s. f.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Vieux mot, qui signifioit la division d'une Note longue, comme une Ronde ou une
					Blanche, en plusieurs autres Notes de moindre valeur. On entendoit encore par ce
					mot tous les Fredons &amp; autres passages qu'on a depuis appellés <RENVOI
					cible="ROULEMENS1">Roulemens</RENVOI> ou <RENVOI cible="ROULADES1"
					>Roulades</RENVOI>. <U_RENVOI>
					<TXTDisparaitre>(Voyez ces mots)</TXTDisparaitre>
					</U_RENVOI> </p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DIOXIE1">
		<CDI>
			<ITEM>DIOXIE</ITEM>
			<U_GRAMMAIRE QUICK="NF">
				<texte>s. f.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>C'est, au rapport de Nicomaque, un nom que les Anciens donnoient quelquefois à
					la Consonnance de la Quinte, qu'ils appelloient plus communément
					<italic>Diapente</italic>. <U_RENVOI>
					<TXTDisparaitre>(Voyez</TXTDisparaitre>
					<RENVOI cible="DIAPENTE1">DIAPENTE</RENVOI>
					<TXTDisparaitre>.)</TXTDisparaitre>
					</U_RENVOI> </p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DISJONCTION1">
		<CDI>
			<ITEM>DISJONCTION</ITEM>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>C'étoit, dans l'ancienne Musique, l'espace qui séparoit la Mèse de la Paramèse,
					ou en général un Tétracorde du Tétracorde voisin, lorsqu'ils n'étoient pas
					conjoints. Cet espace étoit d'un Ton, &amp; s'appelloit en Grec
					<italic>Diazeuxis</italic>.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DISSONANCE_MAJEURE1">
		<CDI>
			<ITEM>DISSONANCE MAJEURE</ITEM>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>C'est celle qui se sauve en montant. Cette <ITEM_TRAITE>Dissonance</ITEM_TRAITE> n'est telle
					que relativement à la <italic>Dissonance mineure</italic>; car elle fait. Tierce
					ou Sixte majeure sur le vrai Son fondamental, &amp; n'est autre que la Note
					sensible, dans un Accord Dominant, ou la Sixte-ajoutée dans son Accord.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="NON" id="DISSONANT1">
		<CDI>
			<ITEM>DISSONANT</ITEM>
		</CDI>
		<CDT>
			<DEFINITION>
				<p><italic>partie</italic>. <U_RENVOI>
					<TXTDisparaitre>(Voyez</TXTDisparaitre>
					<RENVOI cible="DISSONNER1">DISSONNER</RENVOI>
					<TXTDisparaitre>.)</TXTDisparaitre>
					</U_RENVOI> </p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DISSONNER1">
		<CDI>
			<ITEM>DISSONNER</ITEM>
			<U_GRAMMAIRE QUICK="v">
				<texte>v. n.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Il n'y a que les Sons qui <ITEM_TRAITE>dissonent</ITEM_TRAITE>, &amp; un Son
					<ITEM_TRAITE>dissone</ITEM_TRAITE> quand il forme Dissonance avec un autre Son. On ne dit
					pas qu'un Intervalle <ITEM_TRAITE>dissone</ITEM_TRAITE>, on dit qu'il est Dissonant.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="AFFETTUOSO1">
		<CDI>
			<ITEM>AFFETTUOSO</ITEM>
			<U_GRAMMAIRE QUICK="adj">
				<texte>adj.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p><italic>Pris adverbialement</italic>. Ce mot écrit à la tête d'un Air indique
					un mouvement moyen entre l'<italic>Andante &amp; l'Adagio</italic>, &amp; dans
					le caractere du Chant une expression affectueuse &amp; douce.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DITON1">
		<CDI>
			<ITEM>DITON</ITEM>
			<U_GRAMMAIRE QUICK="NM">
				<texte>s. m.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>C'est dans la Musique Grecque, un Intervalle composé de deux Tons; c'est-à-dire,
					une Tierce majeure. <U_RENVOI>
					<TXTDisparaitre>(Voyez </TXTDisparaitre>
					<RENVOI cible="INTERVALLE1">INTERVALLE</RENVOI>
					<TXTDisparaitre>,</TXTDisparaitre>
					<RENVOI cible="TIERCE1">TIERCE</RENVOI>
					<TXTDisparaitre>.)</TXTDisparaitre>
					</U_RENVOI> </p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DIX-HUITIEME1">
		<CDI>
			<ITEM>DIX-HUITIEME</ITEM>
			<U_GRAMMAIRE QUICK="NF">
				<texte>s. f.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Intervalle qui comprend dix-sept Degrés conjoints, &amp; par conséquent <ITEM_TRAITE>dix-huit</ITEM_TRAITE>
					Sons Diatoniques en comptant les deux extrêmes. C'est la double Octave de la
					Quarte. <U_RENVOI>
					<TXTDisparaitre>(Voyez </TXTDisparaitre>
					<RENVOI cible="QUARTE1">QUARTE</RENVOI>
					<TXTDisparaitre>)</TXTDisparaitre>
					</U_RENVOI></p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DIX-NEUVIEME1">
		<CDI>
			<ITEM>DIX-NEUVIEME</ITEM>
			<U_GRAMMAIRE QUICK="NF">
				<texte>s. f.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Intervalle qui comprend <ITEM_TRAITE>dix-huit</ITEM_TRAITE> Degrés conjoints, &amp; par conséquent <ITEM_TRAITE>dix-neuf</ITEM_TRAITE>
					Sons Diatoniques en comptant les deux extrêmes. C'est la double Octave de la
					Quinte. <U_RENVOI>
					<TXTDisparaitre>(Voyez </TXTDisparaitre>
					<RENVOI cible="QUINTE1">QUINTE</RENVOI>
					<TXTDisparaitre>.)</TXTDisparaitre>
					</U_RENVOI></p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="AGOGE1">
		<CDI>
			<ITEM>AGOGE</ITEM>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Conduite. Une des subdivisions de l'ancienne Mélopée, laquelle donne les regles
					de la marche du Chant par degrés alternativement conjoints ou disjoints, soit en
					montant, soit en descendant. <U_RENVOI>
					<TXTDisparaitre>(Voyez </TXTDisparaitre>
					<RENVOI cible="MÉLOPÉE1">MÉLOPÉE</RENVOI>
					<TXTDisparaitre>.)</TXTDisparaitre>
					</U_RENVOI> </p>
				<p>Martianus Cappella donne, après Aristide Quintilien, au mot
					<ITEM_TRAITE>Agogé</ITEM_TRAITE>, un autre sens que j'exposé au mot <RENVOI cible="TIRADE1">TIRADE</RENVOI>.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="NON" id="DOLCE1">
		<CDI>
			<ITEM>DOLCE</ITEM>
		</CDI>
		<CDT>
			<DEFINITION>
				<p><U_RENVOI>
					<TXTDisparaitre>(Voyez </TXTDisparaitre>
					<RENVOI cible="D1">D</RENVOI>
					<TXTDisparaitre>.)</TXTDisparaitre>
					</U_RENVOI> </p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DOMINANT1">
		<CDI>
			<ITEM>DOMINANT</ITEM>
			<U_GRAMMAIRE QUICK="adj">
				<texte>adj.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Accord <ITEM_TRAITE>Dominant</ITEM_TRAITE> ou sensible et celui qui se pratique sur la
					<ITEM_TRAITE>Dominante</ITEM_TRAITE> du Ton, &amp; qui annonce la Cadence parfaite. Tout
					Accord parfait majeur devient <ITEM_TRAITE>Dominant</ITEM_TRAITE>, si-tôt qu'on lui ajoute
					la Septieme mineure.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DOMINANTE1">
		<CDI>
			<ITEM>DOMINANTE</ITEM>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Dans le Plain-Chant, est la Note que l'on rebat le plus souvent, à quelque Degré
					que l'on soit de la Tonique. Il y a dans le Plain-Chant <ITEM_TRAITE>Dominante</ITEM_TRAITE> <italic>&amp;
					Tonique</italic>, mais point de Médiante.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DOUBLE1">
		<CDI>
			<ITEM>DOUBLE</ITEM>
			<U_GRAMMAIRE QUICK="adj">
				<texte>adj.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Intervalles <ITEM_TRAITE>Doubles</ITEM_TRAITE> ou <ITEM_TRAITE>redoublés</ITEM_TRAITE> sont tous
					ceux qui excedent l'étendue de l'Octave <ITEM_TRAITE>redoublés</ITEM_TRAITE> sont tous qui excedent de 
					l'Octave. En ce sens la Dixieme est <ITEM_TRAITE>double</ITEM_TRAITE> de la Tierce, &amp;
					la Douzieme <ITEM_TRAITE>double</ITEM_TRAITE> de la Quinte. Quelques-uns donnent aussi le
					nom d'Intervalles <ITEM_TRAITE>doubles</ITEM_TRAITE> à ceux qui sont composés de deux
					Intervalles égaux, comme la Fausse-Quinte qui est composée de deux Tierces
					mineures.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DOUBLER1">
		<CDI>
			<ITEM>DOUBLER</ITEM>
			<U_GRAMMAIRE QUICK="v">
				<texte>v. a.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p><ITEM_TRAITE>Doubler</ITEM_TRAITE> un Air, c'est y faire des Doubles;
				<ITEM_TRAITE>Doubler</ITEM_TRAITE> un rôle, c'est y remplacer l'Acteur principal. <U_RENVOI>
					<TXTDisparaitre>(Voyez </TXTDisparaitre>
					<RENVOI cible="DOUBLE1">DOUBLE</RENVOI>
					<TXTDisparaitre>.)</TXTDisparaitre>
					</U_RENVOI> </p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DOUBLE-CORDE1">
		<CDI>
			<ITEM>DOUBLE-CORDE</ITEM>
			<U_GRAMMAIRE QUICK="NF">
				<texte>s. f.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Maniere de jeu sur le Violon, laquelle consiste à toucher deux cordes à la fois
					faisant deux Parties différentes. La <ITEM_TRAITE>Double-corde</ITEM_TRAITE> fait souvent beaucoup
					d'effet. Il est difficile de jouer très-juste sur la <ITEM_TRAITE>Double-corde</ITEM_TRAITE>.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DOUBLE-OCTAVE1">
		<CDI>
			<ITEM>DOUBLE-OCTAVE</ITEM>
			<U_GRAMMAIRE QUICK="NF">
				<texte>s. f.</texte>
			</U_GRAMMAIRE>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Intervalle composé de deux Octaves, qu'on appelle autrement
					<italic>Quinzieme</italic>, &amp; que les Grecs appelloient
					<italic>Disdiapason</italic>.</p>
				<p>La <ITEM_TRAITE>Double-Octave</ITEM_TRAITE> est en raison doublée de l'Octave simple, &amp;
					c'est le seul Intervalle qui ne change pas de nom en se composant avec
					lui-même.</p>
			</DEFINITION>
		</CDT>
	</ARTICLE>
	<ARTICLE RELU="OUI" id="DOUBLE-TRIPLE1">
		<CDI>
			<ITEM>DOUBLE-TRIPLE</ITEM>
		</CDI>
		<CDT>
			<DEFINITION>
				<p>Ancien nom de la Triple de Blanches ou de la Mesure à trois pour deux, laquelle
					se bat à trois Tems, &amp; contient une Blanche pour chaque Tems. Cette Mesure
